classDiagram

class NodeAttacherLocation {
   +- seed_attacherLocationRaw : PageRaw:AttacherLocation
   +- isActivate : Boolean : show activation status
   ++ cmptNode : CmptNode
   ++ cmptHookNode : CmptHookNode

   + activate(getCmptNodeByCmptRawRefId: Function) --> Boolean : error status

}