classDiagram

class PageRaw {
   ++ tmptHub : TmptHub
   ++ generalInfo : PageGeneralInfo
   ++ meta : PageMeta
   ++ cmptRawBUSH : CmptRawBUSH

   + createCmptRaw () --> CmptRaw
   + addCmptRaw (cmptRaw: CmptRaw) --> Boolean : error status
   + createAndAddCmptRaw () --> Boolean : error status
   + removeCmptRaw (cmptRaw: CmptRaw) --> Boolean : error status
   + getCmptRawByRefId (cmptRawRefId: String) --> CmptRaw
   + toGeneDict () --> Object[String: Object] : geneDict of PageRawObject
   
   + STATIC : fromGeneDict (geneDict: Object, tmptHub: TmptHub) --> PageRaw --> return new PageRaw object. 
   
}


%% Features.........................................
%% - can add CmptRaw
%% - can create new CmptRaw
%% - can create and add in CmptRaw
%% - genebilite (geneable)

