classDiagram
class CmptRaw {
   +- id : Number
   +- refId : String
   +- idLikeClassName : String
   +- tmpt : Tmpt
   +- style : CmptRawStyle
   +- styleConfig : CmptRawStyleConfig
   +- attachingPoint : AttachingPoint
   +- hookNameToHook : Object [String: CmptHookRaw]

}