classDiagram
class CmptHookRaw {
   +- cmptRaw: CmptRaw : BASE
   +- id : Number
   +- refId : String
   +- idLikeClassName : String
   +- name : String
   +- type : String
   +- definedScopes : Array[String]
   +- tmptHook : TmptHook
   +- style : CmptHookRawStyle
   +- styleConfig : CmptHookRawStyleConfig
   +- attacher : Attacher
}