classDiagram
class Attacher {
   +- location : AttacherLocationRaw : GIVEN
   +- isAttached : Boolean

   + attacher () --> null : Generated Implimentation error

   + toGeneDict () --> Object : geneDict of AttacherObject
}