classDiagram
class CmtpTREE {
   + cmptSET : CmptSET
   + inactiveCmptNodes : Array

   + isCmptNodeExistsInTREE (cmptNode : CmptNode) --> Boolean : existance status

   + activateInactiveCmptNodes () --> Boolean : success status
   
   + addCmptNode (cmptNode: CmptNode, activate=true: Boolean)
   
   + removeCmptNode (cmptNode: CmptNode) --> CmptNode
   
   + attachCmptNode (cmptNode: CmptNode, parentCmptNode: CmptNode, hookName: String) --> Boolean : success status

   + dettachCmptNode (cmptNode: CmptNode) --> Boolean : success status

   + moveCmptNode (cmptNode: cmptNode, parentCmptNode: CmptNode, hookName: String) --> Boolean : success status

   - _createCmptSET () --> CmptSET

}