classDiagram
class TextAttacher__Attacher {
   +- text : String

   + attach (text: String) --> Boolean : error status

   + attachText (text: String) --> Boolean : error status

   + toGeneDict () --> Object : geneDict of TextAttacher

   + STATIC : fromGeneDict (geneDict: Object, attacherLocationRaw: AttacherLocationRaw) --> TextAttacherObject
}