classDiagram

class Attacher {
   +- seed_attacher : PageRaw:Attacher
   +- location : NodeAttacherLocation
   +- isAttached : Boolean : show attachment props


   + attach () --> NotImplementedError
   + detach () --> NotImplementedError

   + resetAttachmentProps () --> null
}