classDiagram

class HtmlAttacher__Attacher{
   +- isActivated : Boolean
   +- seed_htmlAttacher : PageRaw:HtmlAttacher
   +- attacherType : String
   +- attachedHtml : String

   + activate () --> null
   + attach (html: String) --> Boolean : error status
   + attachToHtml (html: String) --> Boolean: error status

   + detach (html: String) --> Boolean : error status
   + detachFromHtml (html: String) --> Boolean: error status

   + resetAttachmentProps () --> null
   + resetAttachment () --> null
}