classDiagram
class MultiAPAttacher__Attacher {
   +- attachedAPLocCmptRawRefIdList : Array[String] : AttachingPoint.location.cmptRawRefId

   + attach (attachingPoint: AttachingPoint) --> Boolean: error status

   + attachAAttachingPoint (attachingPoint: AttachingPoint) --> Boolean : error status
}