classDiagram
class CmptNodeAttacher {
   [+|-] cmptNode: CmptNode
   [+|-] isAttached : Boolean : shows status of attachment
   [+|-] attachedAtCmpt : Cmpt
   [+|-] attachedAtHook : CmptHook
   [+|-] attachedAtIndex : Number
}