classDiagram
%% MaleAttacher == HookAttacher
class MaleAttacher {
   [+|-] cmptHook : CmptHook : GIVEN
   [+|-] hookType : String : CmptHook.type
   [+|-] isAttached : Boolean : shows attachment status
   [+|-] attachedToCmptRefId : String
   [+|-] attachedToText : String
   [+|-] attachedToHtml : String
   [+|-] attachedToCmptRefIds : Array
   

   + attachTo (value: Cmpt/String) --> Boolean : error status
   
   + attachToCmpt (cmpt: Cmpt) --> Boolean : error status
   
   + attachToText (text: String) --> Boolean : error status
   
   + attachToHtml (html : String) --> Boolean : error status

   + attachACmpt (cmpt: Cmpt) -- Boolean : error status

   + detachFrom (value: Cmpt/String) --> Boolean : error status

   + detachFromCmpt (cmpt: Cmpt) --> Boolean : error status

   + detachFromText (text: String) --> Boolean : error status

   + detachFromHtml (html: String) --> Boolean : error status

   + detachFromACmpt (cmpt: Cmpt) --> Boolean: error status
}