classDiagram
class CmptNodeHookAttacher {
   [+|-] cmptNodeHook : CmptNodeHook
   [+|-] isAttached : Boolean : shows attachment status
   [+|-] attachedToCmptNode : CmptNode
   [+|-] attachedToText : String
   [+|-] attachedToHtml : String
   [+|-] attachedToCmptNodeList : Array[CmptNodes]

   + attachTo (value: cmptNode/String) --> Boolean : error status

   + attachToCmptNode (cmptNode: CmptNode) --> Boolean : error status

   + attachToText (text: String) --> Boolean : error status

   + attachToHtml (html: String) --> Boolean : error status

   + attachACmptNode (cmptNode: CmptNode) --> Boolean : error status


   + detachFrom (value: CmptNode/String) --> Boolean : error status

   + detachFromCmptNode (cmptNode: CmptNode) --> Boolean : error status

   + detachFromText (text: String) --> Boolean : error status

   + detachFromHtml (html: String) --> Boolean : error status

   + detachACmptNode (cmptNode: CmptNode) --> Boolean : error status

}