classDiagram
class FemaleAttacher {
   [+|-] cmpt: Cmpt
   [+|-] isAttached : Boolean : show attachment status
   [+|-] attachedAtCmptRefId : String
   [+|-] attachedAtHookName : String
   [+|-] attachedAtIndex : Number
}