classDiagram
class CmptNode {
   [+|-] id : Number : equal to Cmpt.id
   [+|-] refId : String : equal to Cmpt.refId
   [+|-] isActivated : Boolean : status of Cmpt & Hook Attacher props assignment
   [+|-] cmpt: Cmpt
   [+|-] attacher: CmptAttacher
   [+|-] hookNameToNodeHook : Object [String: CmptHookNode]


   - _createNewCmptAttacher (cmpt: Cmpt) --> CmptAttacher
   - _createHookNameToNodeHook (cmpt: Cmpt) --> Object [String: CmptHookAttacher]
}