classDiagram
class AttachingPoint {
   +- location : AttachingPointLocationRaw : GIVEN
   ++ isAttached : Boolean : shows attachment status
   ++ attachedAttacherLocCmptRawRefId : String : Attacher.location.cmptRawRefId
   ++ attachedAttacherLocHookName : String : Attacher.location.hookName
   ++ attachedAtIndex : Number

   + STATIC: fromGeneDict (geneDict: Object, attachingPointLocationRaw: AttachingPointLocationRaw) --> AttachingPointObject

   + toGeneDict () --> Object : geneDict of AttachingPointObject
}