classDiagram

class AttachingPoint {
   +- seed_attachingPoint : PageRaw:AttachingPoint

   +- isActivate : Boolean
   +- location : NodeAttachingPointLocation

   +- isAttached : Boolean
   +- attachedAtIndex : Integer
   +- attachedAttacher : PageNode:Attacher
   
   + activate (getCmptNodeByCmptRawRefId: Function) --> null
   
   + resetAttachmentProps () --> null
   
}