classDiagram
class CmptHook {
   + id : Number
   + name: String
   + refId: String
   + idLikeClassName : String
   + style : CmptHookStyle
   + styleConfig : CmptHookStyleConfig
   + attacher : CmptHookAttacher
   + base : Cmpt
}