classDiagram
%% DocPage o-- TmptHub
DocPage *-- PageMeta
DocPage *-- PageGeneralInfo
%% TmptPOOL o-- TmptHub
%% DocPage *-- TmptPOOL
DocPage *-- DocCmptNodeTREE


DocCmptNodeTREE *-- CmptNodePOOL
CmptNodePOOL o-- CmptNode
CmptNodePOOL o-- CmptNode


CmptNode o-- DocCmpt

DocCmpt o-- DocTmpt

DocTmpt *-- DocTmptHook
DocTmpt *-- DocTmptHook
DocTmpt *-- DocTmptStyle
DocTmpt *-- DocTmptStyleConfig

DocCmpt *-- DocCmptStyle
DocCmpt *-- DocCmptStyleConfig


DocCmpt *-- DocCmptHook
DocCmpt *-- DocCmptHook
DocCmpt *-- AttachedAt

DocCmptHook *-- AttachedTo
DocCmptHook *-- DocCmptHookStyleConfig
DocCmptHook *-- DocCmptHookStyle


CmptNode o-- CmptAttachment
CmptAttachment o-- DocCmptHook__2
CmptAttachment o-- DocCmpt__2


CmptNode o-- CmptHookAttachment
CmptNode o-- CmptHookAttachment

CmptHookAttachment o-- DocCmpt__3



class DocPage {
   Mother = App
}

class CmptNode {
   Mother = DocPage
}

class DocCmpt {
   Mother = DocPage
}

class CmptAttachment {
   Mother = CmptNode::static
}

class CmptHookAttachment {
   Mother = CmptNode::static
}

class DocTmpt {
   Mother = TmptHub
}



