classDiagram

PageCanvas o-- Page
PageCanvas o-- DocPage

PageCanvas <-- EditPageGeneralInfo

PageCanvas <-- EditPageMeta

PageCanvas <-- EditCmpt
PageCanvas <-- EditCmptHook
PageCanvas <-- EditCmptPosition

EditCmpt *-- CmptStyle
EditCmpt *-- CmptStyleConfig
EditCmpt *-- CmptStyleOnCanvas
EditCmpt *-- CmptStyleConfigOnCanvas

EditCmptHook *-- CmptHookStyle
EditCmptHook *-- CmptHookStyleConfig
EditCmptHook *-- CmptHookStyleOnCanvas
EditCmptHook *-- CmptHookStyleConfigOnCanvas





%% EditPageGeneralInfo
%% EditPageMeta

%% EditCmpt
%% EditCmpt.style
%% EditCmpt.styleOnCanvas
%% EditCmpt.styleConfig
%% EditCmpt.styleConfigOnCanvas

%% EditCmptHook
%% EditCmptHook.style
%% EditCmptHook.styleOnCanvas
%% EditCmptHook.styleConfig
%% EditCmptHook.styleConfigOnCanvas



%% ............................
%% ...........................

%% Feature list of page canvas
%% -> Edit page general info
%% [DONE] PageCanvas.EditPageGeneralInfo

%% -> Edit page meta data
%% [DONE] PageCanvas.EditPageMeta

%% -> Edit cmpt: cmptStyle, cmptStyleConfig
%% [DONE] PageCanvas.EditCmpt.style, PageCanvas.EditCmpt.styleConfig

%% -> Edit cmpthook: cmptHookStyle, cmptHookStyleConfig
%% [DONE] PageCanvas.EditCmptHook.style, PageCanvas.EditCmptHook.styleConfig

%% -> Can be render inside html element
%% [DONE] PageCanvas.renderInsideElmt()

%% -> Can move cmpt
%% [DONE] PageCanvas.EditCmptPosition.move()

%% -> Can add new cmpt
%% [DONE] PageCanvas.createAndAddNewCmpt()

%% -> Can remove cmpt
%% [DONE] PageCanvas.removeCmpt()

%% -> Attach emptyHookFillerCmpt to empty Cmpt Hook. Objective : to add and attach cmpt to hook easy.
%% [DONE] 

%% -> Can add custom style to cmpt html element
%% 

%% -> Can add custom style to cmpt's hooks html element
%% 

%% -> CmptStructure html element to show structure of cmpts in page canvas
%% 

%% 